### ISSUE TITLE
How to determine some parameters in YAML files

### ISSUE THREAD

**Issue by evayfang2019** [PacificBiosciences/paraphase#14]
Hi Dr. Chen, 
I'm curious about some of the settings in the [./data/38/config.yaml](https://github.com/PacificBiosciences/paraphase/blob/main/paraphase/data/38/config.yaml). Could you please tell me some of the details?
Thank you!

Taking Amy1A as an example
----------------------------------------------------------------------------------------
```yaml
AMY1A:
  genes: AMY1A,AMY1B,AMY1C
  realign_region: chr1:103650157-103669000
  extract_regions: chr1:103650158-103668000 chr1:103684093-103701812 chr1:103744296-103762027
  left_boundary: 103650159
  right_boundary: 103667870
  clip_3p_positions: [103667876]
  noisy_region: [[103667000, 103667870]]
  add_sites: ["103667950_T_A"]
  use_supplementary: True
```
genes: name of target gene (AMY1A) and its pseudogene (AMY1B,AMY1C)
realign_region: may be related to the region of AMY1A, and how to determine this specific location?
extract_regions: may be related to the region of AMY1A and its pseudogene (AMY1B,AMY1C), and how to determine?
as well as left_boundary, right_boundary, clip_3p_positions, noisy_region, add_sites, use_supplementary and other parameters?
